name: s3 bucket Sync
on:
  push:
    branches:
      - main
#   schedule:
# # 4 times everyday
#   - cron: "0 */6 * * *"
#  watch:
#    types: [started]

  workflow_dispatch:

jobs:
  douban:
    name: s3 bucket Sync 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Rclone
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    # Ready to Upload
    - name: Remove Ignore files
      run: |
        rm .git -rf
        rm .github -rf

    # Rclone Sync to Tencent Cloud COS
    - name: Rclone Sync to COS
      run: |
          # rclone sync ./ TencentUS:${{ secrets.COS_CDN_US_BUCKET }} --filter newer --max-age 24h --exclude=.git/** --exclude=.github/** --exclude=README.md
          rclone sync ./ TencentCN:${{ secrets.COS_CDN_CN_BUCKET }} --max-age 24h --exclude=.git/** --exclude=.github/** --exclude=README.md
          #rclone sync ./ Cloudflare:${{ secrets.CF_R2_BUCKET }} --max-age 24h --exclude=.git/** --exclude=.github/** --exclude=README.md
          # rclone sync ./ Backblaze:${{ secrets.B2_BUCKET }} --max-age 24h --exclude=.git/** --exclude=.github/** --exclude=README.md
      env:
        RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}

    # Rclone Sync to Cloudflare R2
    - name: Rclone Sync to R2
      run: |
          rclone sync ./ Cloudflare:${{ secrets.CF_R2_BUCKET }} --max-age 24h --exclude=.git/** --exclude=.github/** --exclude=README.md
      env:
        RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
