name: s3 bucket Sync
on:
  push:
    branches:
      - main
#   schedule:
# # 4 times everyday
#   - cron: "0 */6 * * *"
#  watch:
#    types: [started]

  workflow_dispatch:

jobs:
  douban:
    name: s3 bucket Sync 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Rclone
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    # Ready to Upload
    - name: Remove Ignore files
      run: |
        rm .git -rf
        rm .github -rf

    # Rclone Sync to B2 & R2
    - name: Rclone Sync 
      run: |
          rclone sync -u --size-only ./ TencentUS:${{ secrets.COS_CDN_US_BUCKET }} --transfers=8 --checkers=16 --max-age 24h --checksum --exclude=.git/** --exclude=.github/** --exclude=README.md
          rclone sync -u --size-only ./ TencentCN:${{ secrets.COS_CDN_CN_BUCKET }} --transfers=8 --checkers=16 --max-age 24h --checksum --exclude=.git/** --exclude=.github/** --exclude=README.md
          rclone sync -u --size-only ./ Cloudflare:${{ secrets.CF_R2_BUCKET }} --transfers=8 --checkers=16 --max-age 24h --checksum --exclude=.git/** --exclude=.github/** --exclude=README.md
          rclone sync -u --size-only ./ Backblaze:${{ secrets.B2_BUCKET }} --transfers=8 --checkers=16 --max-age 24h --checksum --exclude=.git/** --exclude=.github/** --exclude=README.md
      env:
        RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
